# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egreeting.proto\x12\x07\x65xample\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x10GreetingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xa2\x01\n\x0fGreetingRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08nickName\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03\x64ob\x18\x03 \x01(\tH\x02\x88\x01\x01\x12(\n\x08language\x18\x04 \x01(\x0e\x32\x11.example.LanguageH\x03\x88\x01\x01\x42\x07\n\x05_nameB\x0b\n\t_nickNameB\x06\n\x04_dobB\x0b\n\t_language\"\x18\n\nGreetingId\x12\n\n\x02id\x18\x01 \x01(\x05\"C\n\x14GreetingResponseList\x12+\n\x08response\x18\x01 \x03(\x0b\x32\x19.example.GreetingResponse*4\n\x08Language\x12\x0b\n\x07\x45NGLISH\x10\x00\x12\x0e\n\nPORTUGUESE\x10\x01\x12\x0b\n\x07SPANISH\x10\x02\x32\xb4\x02\n\x0fGreetingService\x12?\n\x08SayHello\x12\x16.google.protobuf.Empty\x1a\x19.example.GreetingResponse\"\x00\x12\x43\n\x12\x44\x65leteHelloMessage\x12\x13.example.GreetingId\x1a\x16.google.protobuf.Empty\"\x00\x12L\n\x13\x46indOneHelloMessage\x12\x18.example.GreetingRequest\x1a\x19.example.GreetingResponse\"\x00\x12M\n\x15\x46indHelloMessagesById\x12\x13.example.GreetingId\x1a\x1d.example.GreetingResponseList\"\x00\x42)\n\x1b\x63om.costa.luiz.grpc.exampleB\x08GreetingP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeting_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.costa.luiz.grpc.exampleB\010GreetingP\001'
  _globals['_LANGUAGE']._serialized_start=353
  _globals['_LANGUAGE']._serialized_end=405
  _globals['_GREETINGRESPONSE']._serialized_start=56
  _globals['_GREETINGRESPONSE']._serialized_end=91
  _globals['_GREETINGREQUEST']._serialized_start=94
  _globals['_GREETINGREQUEST']._serialized_end=256
  _globals['_GREETINGID']._serialized_start=258
  _globals['_GREETINGID']._serialized_end=282
  _globals['_GREETINGRESPONSELIST']._serialized_start=284
  _globals['_GREETINGRESPONSELIST']._serialized_end=351
  _globals['_GREETINGSERVICE']._serialized_start=408
  _globals['_GREETINGSERVICE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
